### ISSUE TITLE
Thrown error when trying to ask/get permissions "const { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL);"

### ISSUE THREAD

**Issue by mburgjr** [deinyefa/RNPhotoPicker#1]
I've implemented the code exactly from the photo-picking screen, yet thrown an error when trying to establish permissions: 

[Unhandled promise rejection: Error: An exception was thrown while calling `ExpoPermissions.askAsync` with arguments `(]
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:155:41 in createErrorFromErrorData
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:414:4 in __invokeCallback
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:127:28 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:314:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:126:17 in invokeCallbackAndReturnFlushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue

Been stuck with this error for some time, tried changing the code implementation but cannot see where it would be wrong. Wondering if something needs to be changed in the installations of "expo-permissions" or "expo-image-picker"

**Comment by mburgjr** [comment]
Logging the exception gives:

An exception was thrown while calling `ExpoPermissions.askAsync` with arguments `(
    cameraRoll
)`: -[NSTaggedPointerString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0xcf282543e6307373
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:104:55 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:414:4 in __invokeCallback
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:127:28 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:314:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:126:17 in invokeCallbackAndReturnFlushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue

**Comment by deinyefa** [comment]
This is probably a version issue. With the latest version of expo, they moved a bunch of functions around and so Permissions is no longer exported directly from expo. Try importing from 'expo-permissions' like:

`import * as Permissions from 'expo-permissions';` of course after installing `expo-permissions`.

I'll need to update this code as it's using a previous version, but here's a guide from [expo](https://docs.expo.io/versions/latest/sdk/permissions/)

**Comment by mburgjr** [comment]
I already made this change for both expo-image-picker and expo-permissions. Everything should be on the latest version too

**Comment by mburgjr** [comment]
Issue is resolved. Needed to be on Expo version 7.0.0, but I was on version 8.0.0
